<a href="https://colab.research.google.com/github/divyalaldinani/Deep-Learning-in-PyTorch/blob/main/Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Learn the basics of Autograd by visting: [this notebook](https://colab.research.google.com/drive/1JswGdhZ8vNZEXKR0v1gRAldIBJdcom7D) or [this video](https://www.youtube.com/watch?v=M0fX15_-xrY&t=14s)

In [1]:
import torch

x = torch.rand(3, requires_grad=True) # must specify requires_grad as True
x

tensor([0.8366, 0.5702, 0.8546], requires_grad=True)

In [2]:
y = x+2
y

tensor([2.8366, 2.5702, 2.8546], grad_fn=<AddBackward0>)

In [3]:
z = y * y * 2
z

tensor([16.0927, 13.2123, 16.2975], grad_fn=<MulBackward0>)

In [4]:
w = z.mean()
w

tensor(15.2008, grad_fn=<MeanBackward0>)

In [5]:
w.backward() #computes gradients backwards from w

In [6]:
x.grad # dz/ dx

tensor([3.7821, 3.4270, 3.8061])

In [7]:
4*y/3

tensor([3.7821, 3.4270, 3.8061], grad_fn=<DivBackward0>)

What if `w` is a tensor?

In [18]:
p = torch.rand(3, requires_grad=True)
q = p+2
r = 2*q*q
v = torch.tensor([0.33333333, 0.33333333, 0.33333333], dtype=torch.float32)

In [19]:
r.backward(v) #v.w

In [20]:
p.grad

tensor([3.6971, 3.0497, 2.8719])

In [22]:
4*q/3

tensor([3.6971, 3.0497, 2.8719], grad_fn=<DivBackward0>)

Turning off requires_grad from a tensor/disabling the creation of gradients for a tensor

In [29]:
x.requires_grad_(False)
x.detach()
x

tensor([0.6247, 0.8119, 0.6901])

In [30]:
with torch.no_grad():
    y = x+2
    print(y)

tensor([2.6247, 2.8119, 2.6901])
