<a href="https://colab.research.google.com/github/divyalaldinani/Deep-Learning-in-PyTorch/blob/main/Tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x = torch.empty(4)
x

tensor([-2.3964e+12,  4.3159e-41, -2.3964e+12,  4.3159e-41])

In [3]:
x.dtype

torch.float32

In [4]:
x.abs()

tensor([2.3964e+12, 4.3159e-41, 2.3964e+12, 4.3159e-41])

In [5]:
y = torch.empty(4)
x.add(y)

tensor([-4.7928e+12,  8.6317e-41, -2.3964e+12,  4.3159e-41])

In [6]:
y

tensor([-2.3964e+12,  4.3159e-41,  9.7716e-34,  0.0000e+00])

In [7]:
x.amax()

tensor(4.3159e-41)

In [8]:
x.amin()

tensor(-2.3964e+12)

In [9]:
x.argmin()

tensor(0)

In [10]:
x.argmax()

tensor(1)

In [11]:
x.angle()

tensor([3.1416, 0.0000, 3.1416, 0.0000])

In [12]:
x.argsort()

tensor([0, 2, 1, 3])

In [13]:
x.argsort(descending=True)

tensor([1, 3, 0, 2])

In [14]:
x = torch.rand(5, 3)
x

tensor([[0.8211, 0.5696, 0.3963],
        [0.5613, 0.7211, 0.3941],
        [0.4961, 0.7468, 0.1768],
        [0.1702, 0.5589, 0.4158],
        [0.2010, 0.2005, 0.4398]])

In [15]:
x = torch.zeros(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [16]:
x.size()

torch.Size([5, 3])

In [17]:
x.dtype

torch.float32

In [18]:
x.shape

torch.Size([5, 3])

In [19]:
x = torch.tensor([0.2, 4])
x

tensor([0.2000, 4.0000])

In [20]:
x = torch.rand(4, 2, 3)
x

tensor([[[0.7722, 0.1474, 0.6951],
         [0.6641, 0.9135, 0.1530]],

        [[0.8643, 0.3316, 0.6435],
         [0.3195, 0.3849, 0.9541]],

        [[0.9854, 0.0033, 0.5704],
         [0.6190, 0.8129, 0.2270]],

        [[0.1372, 0.6806, 0.1717],
         [0.7928, 0.0052, 0.8422]]])

In [21]:
x[:, :, :]

tensor([[[0.7722, 0.1474, 0.6951],
         [0.6641, 0.9135, 0.1530]],

        [[0.8643, 0.3316, 0.6435],
         [0.3195, 0.3849, 0.9541]],

        [[0.9854, 0.0033, 0.5704],
         [0.6190, 0.8129, 0.2270]],

        [[0.1372, 0.6806, 0.1717],
         [0.7928, 0.0052, 0.8422]]])

In [22]:
x[0, :, :]

tensor([[0.7722, 0.1474, 0.6951],
        [0.6641, 0.9135, 0.1530]])

In [23]:
x[:, 0, :]

tensor([[0.7722, 0.1474, 0.6951],
        [0.8643, 0.3316, 0.6435],
        [0.9854, 0.0033, 0.5704],
        [0.1372, 0.6806, 0.1717]])

In [24]:
x[:, :, 1]

tensor([[0.1474, 0.9135],
        [0.3316, 0.3849],
        [0.0033, 0.8129],
        [0.6806, 0.0052]])

In [25]:
x[1, 1, 1].item() # gets the actual value of a particular element in a tensor

0.3849181532859802

In [26]:
x.view(8, 3) # to view a tensor in some shape, note that elements in org tensor = elements in new tensor

tensor([[0.7722, 0.1474, 0.6951],
        [0.6641, 0.9135, 0.1530],
        [0.8643, 0.3316, 0.6435],
        [0.3195, 0.3849, 0.9541],
        [0.9854, 0.0033, 0.5704],
        [0.6190, 0.8129, 0.2270],
        [0.1372, 0.6806, 0.1717],
        [0.7928, 0.0052, 0.8422]])

In [27]:
x

tensor([[[0.7722, 0.1474, 0.6951],
         [0.6641, 0.9135, 0.1530]],

        [[0.8643, 0.3316, 0.6435],
         [0.3195, 0.3849, 0.9541]],

        [[0.9854, 0.0033, 0.5704],
         [0.6190, 0.8129, 0.2270]],

        [[0.1372, 0.6806, 0.1717],
         [0.7928, 0.0052, 0.8422]]])

In [28]:
x.view(-1, 4)

tensor([[0.7722, 0.1474, 0.6951, 0.6641],
        [0.9135, 0.1530, 0.8643, 0.3316],
        [0.6435, 0.3195, 0.3849, 0.9541],
        [0.9854, 0.0033, 0.5704, 0.6190],
        [0.8129, 0.2270, 0.1372, 0.6806],
        [0.1717, 0.7928, 0.0052, 0.8422]])

In [29]:
a = x.numpy()
a

array([[[0.772244  , 0.14735395, 0.69510067],
        [0.6641302 , 0.9134845 , 0.15301937]],

       [[0.8642882 , 0.33162618, 0.6435337 ],
        [0.31950933, 0.38491815, 0.9540867 ]],

       [[0.9853702 , 0.003272  , 0.5703962 ],
        [0.61897665, 0.8128941 , 0.22696364]],

       [[0.13724768, 0.6806337 , 0.17173845],
        [0.792772  , 0.0051977 , 0.8421885 ]]], dtype=float32)

In [30]:
y = torch.from_numpy(a)
y
y = y*2 +5

### Operations on Tensor

In [31]:
x + y

tensor([[[7.3167, 5.4421, 7.0853],
         [6.9924, 7.7405, 5.4591]],

        [[7.5929, 5.9949, 6.9306],
         [5.9585, 6.1548, 7.8623]],

        [[7.9561, 5.0098, 6.7112],
         [6.8569, 7.4387, 5.6809]],

        [[5.4117, 7.0419, 5.5152],
         [7.3783, 5.0156, 7.5266]]])

In [32]:
x.add(y)

tensor([[[7.3167, 5.4421, 7.0853],
         [6.9924, 7.7405, 5.4591]],

        [[7.5929, 5.9949, 6.9306],
         [5.9585, 6.1548, 7.8623]],

        [[7.9561, 5.0098, 6.7112],
         [6.8569, 7.4387, 5.6809]],

        [[5.4117, 7.0419, 5.5152],
         [7.3783, 5.0156, 7.5266]]])

In [33]:
x.mul(y) # dot product / element wise multiplication

tensor([[[5.0539, 0.7802, 4.4418],
         [4.2028, 6.2363, 0.8119]],

        [[5.8154, 1.8781, 4.0459],
         [1.8017, 2.2209, 6.5910]],

        [[6.8688, 0.0164, 3.5027],
         [3.8611, 5.3861, 1.2378]],

        [[0.7239, 4.3297, 0.9177],
         [5.2208, 0.0260, 5.6295]]])

In [34]:
x*y

tensor([[[5.0539, 0.7802, 4.4418],
         [4.2028, 6.2363, 0.8119]],

        [[5.8154, 1.8781, 4.0459],
         [1.8017, 2.2209, 6.5910]],

        [[6.8688, 0.0164, 3.5027],
         [3.8611, 5.3861, 1.2378]],

        [[0.7239, 4.3297, 0.9177],
         [5.2208, 0.0260, 5.6295]]])

In [35]:
x/y # element wise division

tensor([[[0.1180, 0.0278, 0.1088],
         [0.1049, 0.1338, 0.0288]],

        [[0.1285, 0.0586, 0.1024],
         [0.0567, 0.0667, 0.1381]],

        [[0.1414, 0.0007, 0.0929],
         [0.0992, 0.1227, 0.0416]],

        [[0.0260, 0.1070, 0.0321],
         [0.1204, 0.0010, 0.1260]]])

In [36]:
x.div(y)

tensor([[[0.1180, 0.0278, 0.1088],
         [0.1049, 0.1338, 0.0288]],

        [[0.1285, 0.0586, 0.1024],
         [0.0567, 0.0667, 0.1381]],

        [[0.1414, 0.0007, 0.0929],
         [0.0992, 0.1227, 0.0416]],

        [[0.0260, 0.1070, 0.0321],
         [0.1204, 0.0010, 0.1260]]])

### Moving tensors on GPU

**Make sure that if you are running it on colab then runtime type, GPU is enabled.**

In [37]:
x_gpu = x.to('cuda')
x_gpu

tensor([[[0.7722, 0.1474, 0.6951],
         [0.6641, 0.9135, 0.1530]],

        [[0.8643, 0.3316, 0.6435],
         [0.3195, 0.3849, 0.9541]],

        [[0.9854, 0.0033, 0.5704],
         [0.6190, 0.8129, 0.2270]],

        [[0.1372, 0.6806, 0.1717],
         [0.7928, 0.0052, 0.8422]]], device='cuda:0')

In [39]:
y_gpu = y.to('cuda')
y_gpu

tensor([[[6.5445, 5.2947, 6.3902],
         [6.3283, 6.8270, 5.3060]],

        [[6.7286, 5.6633, 6.2871],
         [5.6390, 5.7698, 6.9082]],

        [[6.9707, 5.0065, 6.1408],
         [6.2380, 6.6258, 5.4539]],

        [[5.2745, 6.3613, 5.3435],
         [6.5855, 5.0104, 6.6844]]], device='cuda:0')

In [40]:
z = torch.tensor(x+y, device='cuda')

<ipython-input-40-97fd4530f4c7>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  z = torch.tensor(x+y, device='cuda')


In [41]:
z

tensor([[[7.3167, 5.4421, 7.0853],
         [6.9924, 7.7405, 5.4591]],

        [[7.5929, 5.9949, 6.9306],
         [5.9585, 6.1548, 7.8623]],

        [[7.9561, 5.0098, 6.7112],
         [6.8569, 7.4387, 5.6809]],

        [[5.4117, 7.0419, 5.5152],
         [7.3783, 5.0156, 7.5266]]], device='cuda:0')

Enabling all tensors to run on GPU

In [44]:
torch.set_default_tensor_type(torch.cuda.FloatTensor)
# torch.set_default_tensor_type(torch.cuda.FloatTensor)

In [45]:
a = torch.rand(5, 3)
a

tensor([[0.1775, 0.0516, 0.7139],
        [0.3404, 0.1814, 0.2029],
        [0.4098, 0.5411, 0.7437],
        [0.1526, 0.7579, 0.6562],
        [0.2447, 0.3754, 0.9121]])

In [46]:
a.device # running on CUDA/GPU

device(type='cuda', index=0)